export const FEATURE = {
  BIESSE_ORDERS: 'biesse.orders',
  BIESSE_SCAN: 'biesse.scan',
  BIESSE_STICKERS: 'biesse.stickers',
  BIESSE_TOOLS: 'biesse.tools',
  BIESSE_AUDIT: 'biesse.audit',
  EMPLOYEE_ADMIN: 'employee.admin',
  EMPLOYEE_PROFILE: 'employee.profile',
  EMPLOYEE_AUDIT: 'employee.audit',
  LOCATION_CATALOG: 'location.catalog',
  PALES_LIST: 'pales.list',
  PALES_OPERACIONES: 'pales.operaciones',
  PALES_AUDIT: 'pales.audit',
  PALES_PRINT: 'pales.print',
  TRANSPORT_VEHICLES: 'transport.vehicles',
  TRANSPORT_LOADS: 'transport.loads',
  TRANSPORT_AUDIT: 'transport.audit',
  API_CATALOG: 'api.catalog',
  INVENTORY: 'inventory',
  PROJECT_LIST: 'project.list',
  DASHBOARD_RESUMEN: 'dashboard.resumen',
}

export const ENDPOINT_CATALOG = [
  {
    module: 'module-biesse',
    feature: FEATURE.BIESSE_ORDERS,
    endpoints: [
      ['GET', '/api/biesse/scan/parts/pending'],
      ['POST', '/api/biesse/scan/parts/scan'],
      ['POST', '/api/biesse/scan/pieces/scan'],
      ['GET', '/api/biesse/scan/users/me/stats'],
      ['GET', '/api/biesse/scan/parts/scanned/me'],
      ['GET', '/api/biesse/scan/orders'],
      ['GET', '/api/biesse/scan/orders/{orderId}'],
      ['PATCH', '/api/biesse/scan/orders/{orderId}'],
      ['POST', '/api/biesse/scan/orders/{orderId}/complete'],
      ['GET', '/api/biesse/scan/stats/general'],
      ['GET', '/api/biesse/scan/pieces/resolve'],
      ['GET', '/api/biesse/scan/pieces/{pieceId}'],
      ['GET', '/api/biesse/scan/audit'],
    ],
  },
  {
    module: 'module-system',
    feature: FEATURE.EMPLOYEE_ADMIN,
    endpoints: [
      ['GET', '/api/auth/first-setup/status'],
      ['POST', '/api/auth/first-setup'],
      ['POST', '/api/auth/login'],
      ['POST', '/api/auth/register'],
      ['POST', '/api/auth/refresh'],
      ['POST', '/api/auth/logout'],
      ['POST', '/api/auth/logout-all'],
      ['GET', '/api/auth/me'],
      ['POST', '/api/auth/change-password'],
      ['GET', '/api/employees/me'],
      ['PATCH', '/api/employees/me'],
      ['GET', '/api/employees/{id}'],
      ['GET', '/api/employees'],
      ['POST', '/api/employees'],
      ['PATCH', '/api/employees/{id}'],
      ['PUT', '/api/employees/{id}/roles'],
      ['DELETE', '/api/employees/{id}'],
      ['POST', '/api/employees/{id}/reset-password'],
      ['POST', '/api/impresion/sticker'],
      ['GET', '/api/impresion/sticker'],
      ['GET', '/api/roles'],
      ['GET', '/api/roles/{id}'],
      ['POST', '/api/roles'],
      ['PATCH', '/api/roles/{id}'],
      ['DELETE', '/api/roles/{id}'],
      ['GET', '/api/audit/entries'],
      ['GET', '/api/audit/entries/{id}'],
      ['GET', '/api'],
    ],
  },
  {
    module: 'module-system',
    domain: 'pales',
    feature: FEATURE.PALES_LIST,
    endpoints: [
      ['GET', '/api/pallets/catalogs'],
      ['GET', '/api/pallets'],
      ['POST', '/api/pallets'],
      ['GET', '/api/pallets/{id}'],
      ['PATCH', '/api/pallets/{id}'],
      ['GET', '/api/pallets/by-code/{code}'],
      ['POST', '/api/pallets/{id}/scan-piece'],
      ['POST', '/api/pallets/{id}/close'],
      ['GET', '/api/pallets/audit'],
    ],
  },
  {
    module: 'module-system',
    domain: 'transport',
    feature: FEATURE.TRANSPORT_LOADS,
    endpoints: [
      ['GET', '/api/transport/vehiculos'],
      ['GET', '/api/transport/vehiculos/{id}'],
      ['POST', '/api/transport/vehiculos'],
      ['PUT', '/api/transport/vehiculos/{id}'],
      ['GET', '/api/transport/auditoria'],
    ],
  },
  {
    module: 'module-system',
    domain: 'location',
    feature: FEATURE.LOCATION_CATALOG,
    endpoints: [
      ['GET', '/api/location/branches'],
      ['POST', '/api/location/branch'],
      ['GET', '/api/location/locations'],
      ['POST', '/api/location/location'],
    ],
  },
  {
    module: 'module-system',
    domain: 'rm',
    feature: FEATURE.INVENTORY,
    endpoints: [
      ['POST', '/api/rm/registros-entrada'],
      ['GET', '/api/rm/registros-entrada'],
      ['GET', '/api/rm/registros-entrada/{id}'],
      ['POST', '/api/rm/registros-salida'],
      ['GET', '/api/rm/registros-salida'],
      ['GET', '/api/rm/registros-salida/{id}'],
      ['POST', '/api/rm/actas-conformidad'],
      ['GET', '/api/rm/actas-conformidad'],
      ['GET', '/api/rm/actas-conformidad/{id}'],
      ['POST', '/api/rm/registros-vehiculo'],
      ['GET', '/api/rm/registros-vehiculo'],
      ['GET', '/api/rm/registros-vehiculo/{id}'],
      ['GET', '/api/rm/media/{kind}/{recordId}/{filename}'],
    ],
  },
  {
    module: 'module-system',
    domain: 'inventory',
    feature: FEATURE.INVENTORY,
    endpoints: [
      ['GET', '/api/inventory/categorias'],
      ['GET', '/api/inventory/items'],
      ['GET', '/api/inventory/items/{id}'],
      ['POST', '/api/inventory/items'],
      ['POST', '/api/inventory/items/{id}/movements'],
      ['GET', '/api/inventory/guias'],
      ['GET', '/api/inventory/guias/pales-escaneados'],
      ['GET', '/api/inventory/guias/{id}'],
      ['POST', '/api/inventory/guias'],
      ['PUT', '/api/inventory/guias/{id}'],
      ['POST', '/api/inventory/guias/{id}/detalles'],
      ['POST', '/api/inventory/guias/{id}/detalles/pale'],
      ['DELETE', '/api/inventory/guias/{id}/detalles/{detalleId}'],
    ],
  },
]
